py27 fails for networking-vsphere repo due to deprecation of constants, exceptions and attributes.
py27 errors are seen in networking-vsphere repo.

Exceptions and attributes are deprecated by commit:
https://review.openstack.org/#/c/394201/

Due to this exceptions are seen in py27 logs
AttributeError: 'module' object has no attribute 'validators'

Change-Id: If26de122b704ddebb17d5528463cd6c72c175d4a
Closes-Bug: #1641032