Fix the CLI unit test format specifier failure
Fixes the CLITestV20ExtensionOVSvAppClusterJSON.test_create_ovsvapp_clusters
test failure:

Traceback (most recent call last):
  File "networking_vsphere/tests/unit/neutronclient/test_cli_ovsvapp_cluster.py", line 70, in test_create_ovsvapp_clusters
    position_names, position_values)
  File "networking_vsphere/tests/unit/neutronclient/test_cli20.py", line 69, in _test_create_resource
    self.client.format = self.format
AttributeError: 'CLITestV20ExtensionOVSvAppClusterJSON' object has no attribute 'format'

, due to this change in python-neutronclient:
https://review.openstack.org/#/c/452488.

Change-Id: I836626295b7215327befc7bd4907dfc3927e1c28