ImportError: No module named vine.five
Pin kombu to < 4.0.0

References: https://review.openstack.org/#/c/392103

Closes-Bug: 1650517
(cherry picked from commit ab79fc1bb36f514da2a7b3ac3c85031c48533215)

Conflicts:
	test-requirements.txt

Change-Id: I2f532242290cf634ca1d84d56b05ea56bd921312