Updated the mock version
This is required to fix this issue:
orig_start = mock._patch.start
AttributeError: 'module' object has no attribute '_patch'

Reference:
https://github.com/openstack/neutron/commit/1b60df85ba3ad442c2e4e7e52538e1b9a1bf9378

Change-Id: Ib1bc4d7b57cea8187a780a6976c3a03f4063a72e