TypeError: from_image() takes exactly 4 arguments (3 given)
Because of changes in nova, from_image() method is looking for
4 arguments but 3 is given.

This patch set resolves the issue by passing one more parameter
to from_image() method.

Change-Id: I41f05c1f8d73696bebd9a858c9680a7397291d79
Reference: https://github.com/openstack/nova/blob/master/nova/virt/vmwareapi/images.py#L114