Flows are not getting updated after restart of openvswitch
openvswitch flows are not getting updated in any of the bridges
after restart of openvswitch in ovsvapp.

This patch set resolves this issue by removing the ports from cache
before doing firewall refresh.

Also fixed UT issue: ImportError: cannot import name context
References: https://review.openstack.org/#/c/388157

Change-Id: Ieab7e18651b644fd0a3b42a3425b66778588e555
Closes-Bug: #1669287