Fix spawn method in ovsvapp_vmops.py
This patch is basically to fix spawn method as per Nova changes in
https://github.com/openstack/nova/blob/master/nova/virt/vmwareapi/vmops.py#L631

AttributeError: 'NoneType' object has no attribute 'storage_policy'
Reference:
http://15.126.220.115/OVSVAPP-VXLAN/27450/206065/a66f2bf0c33484fc0c49d4d21b05bcc6ce81da69/controllerlog/screen-n-cpu.log.gz?level=INFO

Change-Id: I9c6b26b8762073282cc3d4f7aa0c13f1abe21e64