ImportError: cannot import name context
From neutron context is removed and put it in neutron_lib
References: https://review.openstack.org/#/c/388157

Change-Id: I9fed559684c336949e2d58dd4414daaecbf9c4f2