ImportError: cannot import name config
agent common config is moved to neutron/conf/agent/common allow
centralization of all configuration options and provide an easy
way to import.

Reference: https://review.openstack.org/#/c/343045/

Change-Id: I263c034a71ec4f3d9549adf51eeca67b73b36a62
Closes-Bug: #1674227