Revert "ImportError: cannot import name context"
This reverts commit 6b0deba5fd2756e12084d7d3c75094c5f44991d3.

Change-Id: Ie64bce83deb56fa86741e0ec920df6359ad76ede